version: '3'

services:
  # Database
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wp-dev-env

  # Database administration
  phpmyadmin:
    depends_on:
      - mysql 
    image: phpmyadmin:latest
    restart: always
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wp-dev-env

  # CMS
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - '80:80'
    restart: always
    env_file: .env
    volumes: ['./wordpress:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wp-dev-env

networks:
  wp-dev-env:
volumes:
  mysql_data:
